---
- name: Gather OS and Version on Docker Servers
  hosts: docker_servers
  become: true
  become_user: root
  gather_facts: yes

  tasks:
    - name: Show OS and Version
      debug:
        msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Get list of available updates
      apt:
        update_cache: yes
        upgrade: 'no'
      register: apt_update_result

    - name: List available updates
      shell: apt list --upgradable
      register: upgradable_packages
      changed_when: false

    - name: Show available updates
      debug:
        msg: "{{ upgradable_packages.stdout_lines }}"
      when: upgradable_packages.stdout_lines | length > 0
      failed_when: false
      ignore_errors: yes
    - name: Notify if no updates are available
      debug:
        msg: "No updates are available."
      when: upgradable_packages.stdout_lines | length == 0

    - name: Docker pull latest images for running containers
      community.docker.docker_compose_v2:
      project_src: "{{ lookup('env', 'HOME') }}/docker/docker-compose-{{ inventory_hostname }}.yml"
      pull: true

    - name: Notify Docker images updated
      debug:
        msg: "Docker images have been pulled and updated."
      when: ansible_distribution == "Ubuntu"

    - name: Restart Docker containers with latest images
      community.docker.docker_compose_v2:
      project_src: "{{ lookup('env', 'HOME') }}/docker/docker-compose-{{ inventory_hostname }}.yml"
      restarted: yes
      when: ansible_distribution == "Ubuntu"
